# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1469793653);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1469793773);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1469793290);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1469793533);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1469793410);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1469513000);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1469793238659");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1469794961659");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1469793245910");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1469796845910");
user_pref("browser.search.countryCode", "KE");
user_pref("browser.search.region", "KE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160414065608");
user_pref("browser.slowStartup.averageTime", 30279);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160414065608");
user_pref("browser.startup.homepage_override.mstone", "45.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":1}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\"]},\"seen\":[\"loop-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"PanelUI-contents\"],\"currentVersion\":5,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1468996961635");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1468910636339");
user_pref("datareporting.policy.firstRunTime", "1468910561634");
user_pref("datareporting.sessions.current.activeTicks", 68);
user_pref("datareporting.sessions.current.firstPaint", 47572);
user_pref("datareporting.sessions.current.main", 2905);
user_pref("datareporting.sessions.current.sessionRestored", 45739);
user_pref("datareporting.sessions.current.startTime", "1469793145013");
user_pref("datareporting.sessions.current.totalTime", 669);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.1", "{\"s\":1469512387126,\"a\":356,\"t\":7112,\"c\":true,\"m\":2379,\"fp\":21384,\"sr\":20840}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1469793655);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "45.0.2");
user_pref("extensions.lastPlatformVersion", "45.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1460620815000}},\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465218002000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465218003000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.0.2\",\"st\":1460620814000},\"langpack-fr@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-fr@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465218020000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597402000}}}");
user_pref("gecko.buildID", "20160414065608");
user_pref("gecko.mstone", "45.0.2");
user_pref("idle.lastDailyNotification", 1469793867);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1468910656);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160414065608");
user_pref("media.gmp-manager.lastCheck", 1469793258);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1469515747);
user_pref("places.history.expiration.transient_current_max_pages", 22811);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1469515747);
user_pref("toolkit.startup.last_success", 1469793147);
user_pref("toolkit.telemetry.cachedClientID", "dbda1724-898c-4e5c-a9f8-7ca960b082b1");
user_pref("toolkit.telemetry.previousBuildID", "20160414065608");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
